useDotenv: true
org: saatwik
app: serverless-app
service: emotional-echo
configValidationMode: error

frameworkVersion: '4'

provider:
  name: aws
  stage: dev
  region: ap-south-1
  stackName: emotional-echo
  runtime: python3.12

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!requirements.txt"
    - "!package.json"


functions:
  emotional_echo:
    handler: lambda_function.lambda_handler
    timeout: 30
    name: ${self:service}-${self:provider.stage} # Corrected variable syntax
    architecture: x86_64
    package:
      patterns:
        - lambda_function.py
        - requirements.txt
        - common_helpers.py
        - mood_enhancer.py
        - person_mood_detector.py
    events:
      - http:
          path: /detect_mood
          method: post
          cors: true
      - http:
          path: /recommend
          method: post
          cors: true
    environment:
      google_gemini_api_key: ${env:GOOGLE_GEMINI_API_KEY}

plugins:
  - serverless-python-requirements


resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: emotional-echo # Custom name for the API Gateway