name: Deploy emotional-echo-project CI
on:
  push:
    branches:
      - main

jobs:
  dev-deploy:
    name: development-deploy
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    env:
        GOOGLE_GEMINI_API_KEY: ${{ secrets.GOOGLE_GEMINI_API_KEY }}

    steps:
        - uses: actions/checkout@v4
        - name: Use Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.13"
        - uses: actions/checkout@v4
        - name: Use Node.js 
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - run: npm install
        - name: Deploy
          run: npx serverless deploy --stage dev --region ap-south-1
          env:
            # testing new things
            SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
            