name: Deploy emotional-echo-project CI
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: development-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
        GOOGLE_GEMINI_API_KEY: ${{ secrets.GOOGLE_GEMINI_API_KEY }}

    strategy:
            matrix:
              python-version: ["3.12"]
              node-version: [20.x]
    # This is not working we need to redesign the file
    steps:
        - uses: actions/checkout@v4
        - name: Use Python ${{matrix.python-version}}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version}}
        - uses: actions/checkout@v4
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm shrinkwrap
        - run: npm install
        - run: npm ci
        - name: Deploy
          uses: serverless/github-action@v4
          with:
            args: deploy --verbose
          env:
            # testing new things
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
            